# -*- coding: utf-8 -*-
"""Ejercicio 4 - CPD - Ames Anapán José

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOFlvrYs5_-UB97evviDLX4B7xach7CG
"""

import concurrent.futures

def calcular_suma(n):
    suma = sum(range(1, n+1))
    print(f"La suma de los números del 1 al {n} es: {suma}")

def main():
    # Definir el número de hilos a utilizar
    num_hilos = 5

    # Crear un ThreadPoolExecutor con el número de hilos especificado
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_hilos) as executor:
        # Lanzar las tareas en paralelo para calcular la suma de números del 1 al 10
        resultados = [executor.submit(calcular_suma, 10) for _ in range(num_hilos)]

        # Esperar a que todas las tareas se completen
        for resultado in concurrent.futures.as_completed(resultados):
            resultado.result()

if __name__ == "__main__":
    main()

"""Este programa se tiene que crear con el comando concurrent.futures, con un número específico de hilos (en este caso, 5), y luego tenemos que lanzar varias tareas en paralelo para calcular la suma de los números del 1 al 10 en cada hilo. Finalmente, vamos a esperar a que todas las tareas se completen y muestra los resultados."""